### ISSUE TITLE
Validate submissions and compute score.

### ISSUE THREAD

**Issue by sbrodehl** [sbrodehl/Hashcode2k18#1]
For a given submission file:

- [x] validate the file
- [x] compute the score

**Comment by PicoJr** [comment]
Hello,

I have written a score calculator and validator (<https://github.com/PicoJr/2018-hashcode-score>)

`python3 main.py --out output/d_metropolis.out --solver greedy input/d_metropolis.in`

`python3 score.py input/d_metropolis.in output/d_metropolis.out_31082 --check --rides --score --wait`

```
INFO:root:checking vehicles
INFO:root:vehicles: OK
INFO:root:checking ride ids
INFO:root:ride ids: OK
score: 1,246,347 = 1,244,889 + 1,458 (bonus)
wait time: 13,112,331
rides: 10,000 = 3,855 (taken) + 6,145 (unassigned) 2,827 (late)
rides: 3,855 (taken) = 729 (bonus) + 3,126 (no bonus)
```

best regards,
PicoJr.

**Comment by sbrodehl** [comment]
Nicely done!  👍 
I think we can use this for #2 , if you don't mind.

**Comment by PicoJr** [comment]
Hello,
You are welcome to use my code =) feel free to fork it.

Best regards,
PicoJr.
